FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY apps/admin/package.json ./apps/admin/
COPY packages/shared/package.json ./packages/shared/

RUN npm install

COPY . .

RUN npx turbo run build --filter=@sauci/shared

WORKDIR /app/apps/admin

EXPOSE 3001

CMD ["npm", "run", "dev"]
